### ISSUE TITLE
Can I request a kustomize-manifests dockerfile?

### ISSUE THREAD

**Issue by zerox12311** [seifrajhi/ci-cd-demo-gitops#1]
Hello! I am a tech enthusiast passionate about software development and continuous integration. I am currently exploring how to update the manifests in ArgoCD using DroneCI and have encountered some challenges in this process.

Recently, I came across your article featuring the rajhisaifeddine/kustomize-manifests:latest Docker image, which seems to be the perfect solution for my needs. Your article and image have been a great inspiration to me, and I believe it could be the key to resolving my current issue.

Therefore, I would greatly appreciate it if you could share the original Dockerfile of this Docker image with me. I believe that by studying and understanding your Dockerfile, I can better grasp the entire process and apply it to my current project.

I understand this might be the result of your hard work, and I assure you that I will fully respect your intellectual property and promise to use it solely for learning and research purposes.

I look forward to your response and thank you in advance for your generous sharing and assistance.

Best regards,

**Comment by seifrajhi** [comment]
Hello @zerox12311 
Hope you are well


I am sorry for late reply .. I forked that repo and built that image: fork is here: https://github.com/seifrajhi/update-kustomization

**Comment by seifrajhi** [comment]
Can I close this issue if you have the resources you look for ? 😄

**Comment by zerox12311** [comment]
@seifrajhi 
Thank you very much for sharing the source code!
Your help is greatly appreciated!
This issue can be close~ Thanks again!
